name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: devdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências do backend
        working-directory: server
        run: npm install

      - name: Rodar migrations e seeds
        working-directory: server
        env:
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USER: devuser
          PG_PASSWORD: devpass
          PG_DATABASE: devdb
        run: |
          npx ts-node src/scripts/create-tables.ts
          npx ts-node src/scripts/seed.ts

      - name: Rodar testes da API (Playwright)
        working-directory: server
        run: |
          npm install
          npx playwright install --with-deps
          npx playwright test

      - name: Instalar dependências do frontend
        working-directory: client
        run: npm install

      - name: Rodar testes da interface (Playwright)
        working-directory: client
        run: |
          npx playwright install --with-deps
          npx playwright test

      - name: Build frontend
        working-directory: client
        run: npm run build
